# Generated by Django 5.0.2 on 2024-02-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='primary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.DeleteModel(
            name='PrimaryGroup',
        ),
    ]
