# Generated by Django 5.0.2 on 2024-02-18 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Москва', max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house', models.CharField(max_length=255, verbose_name='Дом')),
                ('frame', models.CharField(blank=True, max_length=255, verbose_name='Корпус')),
                ('structure', models.CharField(blank=True, max_length=255, verbose_name='Строение')),
                ('floor', models.CharField(max_length=255, verbose_name='Этаж')),
                ('apartment', models.CharField(max_length=255, verbose_name='Квартира')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='Код домофона')),
            ],
            options={
                'verbose_name': 'Адрес заказа',
                'verbose_name_plural': 'Адреса заказов',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='dishes/', verbose_name='Фото')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активен')),
                ('isBestseller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('isNew', models.BooleanField(default=False, verbose_name='Новый товар')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказа',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255, verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='PromotionalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Промокод')),
                ('discount', models.PositiveSmallIntegerField(verbose_name='Процент скидки')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.BooleanField(verbose_name='Аноним')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=14, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_delivery', models.DateTimeField(blank=True, verbose_name='Время доставки')),
                ('cutlery', models.PositiveSmallIntegerField(verbose_name='Количество столовых приборов')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.address', verbose_name='Адрес')),
                ('menu', models.ManyToManyField(to='orders.dish', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
