# Generated by Django 5.0.2 on 2024-02-18 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='dishes/', verbose_name='Фото')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активен')),
                ('isBestseller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('isNew', models.BooleanField(default=False, verbose_name='Новый товар')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
